### ISSUE TITLE
/nlgroupsinviteplayer group-name owner playername doesn't work

### ISSUE THREAD

**Issue by drjawa** [Civcraft/NameLayer#11]
>You do not have permissions to modify this group.

The ability to add other owners is dangerous player wise, but this would be a good enhancement regardless.

**Comment by drjawa** [comment]
Ninja fixed by rourke.

https://github.com/Civcraft/NameLayer/commit/de3f162db40337940d83fc45ffe92edce25aaf01

**Comment by rourke750** [comment]
Owners can just give themselves the permission anyways :/
