### ISSUE TITLE
Problems with setting up fresh NameLayer

### ISSUE THREAD

**Issue by suirad** [Civcraft/NameLayer#117]
Since i've actually started trying to use namelayer for groups and stuff on my test server, anytime i use a /nl command i get a NullPointerException. I request if someone with more experience with NL please load up a freshly cloned jar, and load it up on a mc server with a fresh sqldb. Anytime my i do anything related to NL groups in Citadel or JukeAlert, it errors out. Example below trying /ctr:
(All plugins give a similar error when doing group things)
![Error pic](http://i.gyazo.com/8d29e5fd4919b04d35f31e07cd8bb098.png)

Now i have tried tracing back the null error and band-aiding it by catching it as it happens, in case it was just a missed null on new setups; but that results in false functionality. ie doing a /nlcg tells me it makes the group, even though nothing actually happpens.(after just catching the nulls)

@ProgrammerDan @rourke750

**Comment by rourke750** [comment]
Look at load up and are there any stacks?

**Comment by suirad** [comment]
Load/unload/enable/disable are all working fine with no error. Also actual name tracking is functioning(i checked the sql db)

**Comment by rourke750** [comment]
You sure you have the latest plugins?

**Comment by rourke750** [comment]
The line of error doesnt match with anything: https://github.com/Civcraft/NameLayer/blob/master/src/vg/civcraft/mc/namelayer/GroupManager.java#L222

**Comment by suirad** [comment]
I knew i shoulda put up a ss of the NL itself. Citadel and juke alert were both compiled from Civcraft master repos. NL is my working copy i last committed.
I just got into bed for the night (its 1245am here), if you wanna wait till tomorrow i can give more ss of the error. But if you don't wanna wait id say load NL n civmodcore on a fresh server and play with group commands.

**Comment by jjj5311** [comment]
@rourke750  is enabling commands still a thing somewhere within namelayer?

**Comment by rourke750** [comment]
Yes. It should be in the command package.

**Comment by jjj5311** [comment]
i meant from the config

**Comment by rourke750** [comment]
Resolved https://github.com/Civcraft/NameLayer/commit/b397daf1e6f8372d08007dc75a7c25b245fa3a38

I don't even understand.

**Comment by ProgrammerDan** [comment]
[Maybe this? (see comment)](https://github.com/Civcraft/NameLayer/commit/b397daf1e6f8372d08007dc75a7c25b245fa3a38)
