### ISSUE TITLE
Please let us mute group chats without muting the snitches on that group

### ISSUE THREAD

**Issue by Sanwi** [Civcraft/NameLayer#123]
I'm on 24 pages of groups, and it gets pretty annoying when there are multiple group conversations going on at once.

**Comment by BlackXnt** [comment]
What command are you using?

/ignoregroup should only mute the chat and /jamute should only mute the snitches.

**Comment by Sanwi** [comment]
I didn't realize there was even a command for it. You might want to put it on the wiki.

**Comment by ttk2** [comment]
it is missing from the jukealert wiki?

**Comment by jjj5311** [comment]
be very strange if it was, that has been a feature for a very long time

**Comment by Sanwi** [comment]
Yeah, apparently /ignoregroup does not work AT ALL. Neither does /ignore for players.

**Comment by jjj5311** [comment]
try on civtest, fixes for this were just recently done

**Comment by rourke750** [comment]
Also this should be a CivChat issue not NameLayer.

**Comment by GavJenks** [comment]
tfw I find this on google trying to learn how to mute a group, from 4 years ago, and there still is no documentation of a mute group command in either of the two projects to this day

**Comment by Maxopoly** [comment]
@GavJenks https://github.com/CivClassic/CivChat2/blob/master/plugin.yml#L16

**Comment by GavJenks** [comment]
@Maxopoly I know, I figured that out from the discussion above, but it's still not documented:

https://github.com/Civcraft/NameLayer/wiki (and devoted has a wiki too that just gives a 404)
