### ISSUE TITLE
Allow force cache of Player Name on start up.

### ISSUE THREAD

**Issue by rourke750** [Civcraft/NameLayer#124]

**Comment by jjj5311** [comment]
so on enable do all the things and make a playername list? or do we need them linked to UUID?

**Comment by rourke750** [comment]
I'm actually going to do this.  Some code is not here that should have been here which is now annoying me that it isn't, so I'm going to do it.

@erocs I swear the caching stuff was there.

**Comment by ttk2** [comment]
So this is the issue for caching names on launch and cahcing things in general (groups or names)
