### ISSUE TITLE
[Minor] Decoupling NameLayer permissions

### ISSUE THREAD

**Issue by AkariAkaori** [Civcraft/NameLayer#125]
I noticed that DOORS, CHESTS, BLOCKS and CROPS are Citadel specific permissions, shouldn't plugin-specific permissions be managed by their plugin, perhaps with a NameLayer permissions API, so dependent plugins like CivChat or Bastions could define their own perms without modifying NameLayer itself?

**Comment by ProgrammerDan** [comment]
This is an excellent idea, some kind of permission registration system within NameLayer. Would have to figure out the storage/persistence of those registrations, opens up a proverbial can of worms, but it's a good idea.

**Comment by gipsy-king** [comment]
Agree, great idea. I imagine factories and the future contraptions benefitting from this.

**Comment by rourke750** [comment]
I've always wanted to do this but I've never though of a good system.  Is there some way to do it that doesn't involve using Strings?

**Comment by WildWeazel** [comment]
GUIDs

**Comment by ProgrammerDan** [comment]
Hmm. Stumping for Postgresql: http://www.postgresql.org/docs/8.3/static/datatype-uuid.html

MySQL (grumble): https://dev.mysql.com/doc/refman/5.0/en/miscellaneous-functions.html#function_uuid

E.g. in Postgresql UUID (GUID) is a top-level type with its own comparison and indexing abilities. In MySQL it's just a string. With string capabilities. Or you can do fancy work to pack it into a 16 byte number (which Postgresql gives you for free).

In general, @rourke750 these things are either magic strings or magic numbers. This isn't all bad. GUID is nice, we could provide a resource for a plugin to register its own GUID with NameLayer, give it some descriptive jazz for pretty printing, default levels-of-application, etc.

**Comment by erocs** [comment]
Plugins use MySql. NameLayer already lists all permissions in a single
string field. Why can't plugins register more permissions which just get
added to that string (barring the inevitable maximum length for that field
in the DB, for which a fix should be created if this is supported). Better
yet, why doesn't NameLayer farm permission management out to PEX so we
don't have to deal with it? Create an abstraction layer for permissions in
NameLayer and have a NameLayer based manager + a PEX based manager which
could be selected via config.

**Comment by ProgrammerDan** [comment]
> Plugins use MySql.

I know. I hate it. Not pulling punches here, Postgres is superior in every way.

> PEX 

Makes a lot of sense, would probably be a good approach.

**Comment by rourke750** [comment]
Don't forget other people use this plugin.  By using pex as a dependency we could put other servers in a tough situation.

**Comment by erocs** [comment]
Thus why the permissions layer is abstracted away with a
NameLayerPermissionManager for those servers.

**Comment by erocs** [comment]
Re: Dan & Postgres

Agreed, that's why the AuxBox uses Postgres. Migrating all the plugins
would be a huge pain though.

**Comment by ProgrammerDan** [comment]
Re: Postgres

Yeah. I can't even think about it seriously until all the plugins are using a sensible DB connection pool manager, probably hosted in Civmodcore. Then we could talk about DB conversion, but it's a mess no matter how you slice.

Reg: PEX

I appreciate that other people are using the plugin and we don't want to alienate them, but significantly improving the plugin by having better permission handling, and abstraction like 'rocs is suggesting, can only make life better for everyone (probably). What kind of resistance would you expect, especially if we document the change well?

**Comment by ttk2** [comment]
just lots of confused people, in general we just want to avoid tight coupling and dependencies where possible.

**Comment by rourke750** [comment]
Coming back to this, going to start defining group permissions that get stored with player and then we just check the player for the permission.

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/NameLayer/pull/191
