### ISSUE TITLE
Unable to remove bastion permission in group

### ISSUE THREAD

**Issue by Diet-Cola** [Civcraft/NameLayer#126]
Even when members have 0 permissions, Cannot stop them having bastion access, would be nice to have.

**Comment by ttk2** [comment]
why not just remove them from the group if they have no perms then?

**Comment by ProgrammerDan** [comment]
@rourke750 where did we wind up on this? I know us devs talked a bit somewhere about the granularity of permissions within Namelayer and allowing plugins to "register" their own permission types. This seems somewhat related, perhaps. 

Obviously not a priority relative to sharding, but curious if it's worth pinning or if this should be closed for now.

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/NameLayer/pull/191 Now possible through permission rework
