### ISSUE TITLE
"ITEM isn't a valid reinforcement block" disables reinforcing to another group

### ISSUE THREAD

**Issue by mclemente** [Civcraft/NameLayer#127]
Today I passed my house to another player. While I was changing the control group to the player's own group I kept hitting some blocks I haven't reinforced before. The "Air isn't a valid reinforcement block" message would appear as normal, but I wasn't able to change groups until I /ctr again, but was able to reinforce non-reinforced blocks with stone.

It appears the error message disables passing a reinforcement to another group.

**Comment by ttk2** [comment]
Do we actually support group chagning like this? I thought you had to transfer whole groups at a time.

**Comment by ProgrammerDan** [comment]
It might not be well documented, but any error while in CTR mode exits CTR mode. This is expected behavior. You had nothing selected in your hotbar, hence the air message, and the removal from CTR mode. When transferring in the future, just keep a stack of stone selected and you won't have this issue.

**Comment by gipsy-king** [comment]
Before, you could change both blocks of a double chest to another group, with `/ctr` and empty hand. Can you still do this if you must have the same reinf material in hand to change it?

**Comment by ProgrammerDan** [comment]
You can do it, if and if the chests was previously reinforced.

Here's the success conditions to change a group using /ctr:

1. The target block must be reinforced
1. You must be MOD on both the original block's group and the new group

If (1) is violated, and you have an empty slot selected in your hotbar, you get an "Air isn't a valid reinforcement block" message and /ctr mode ends (without any additional message).

If (2) is violated, you get a Don't have permission message. I believe /ctr mode ends as well.

If (1) is violated but you have a valid reinforcement material selected in your hotbar, the block is reinforced to the new group using one of the valid reinforcement materials.


Hope that clears things up!

**Comment by jjj5311** [comment]
so probably a simple fix when we take player out of ctr mode maybe we should notify them? Sounds pretty convoluted for all the ways you can be removed from ctr

**Comment by ProgrammerDan** [comment]
Yeah probably we could just modify whatever handler returns the "invalid" message and append a "REINFORCEMENT mode ended." message to that same player message.

Easy fix, anyone up for it?

**Comment by jjj5311** [comment]
This issue should have been in citadel pretty sure the case causing problems is here
https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/listener/BlockListener.java#L522

**Comment by ProgrammerDan** [comment]
Yeah, definitely Citadel, good catch. That whole piece needs some cleanup, I see a lot of dangling error handling and edge cases where there is no user feedback, simply quiet failure. That's not good. I don't know what you're working on, but mind taking a closer look at that?

**Comment by jjj5311** [comment]
I can take a look at this now, I have a little spare time right now

**Comment by ProgrammerDan** [comment]
Thanks muchly. Mind if I close this, and you can CopyPasta OP's report into a Citadel issue? 

Thanks again @mclemente for raising this, hopefully we can get some clearer messaging.
