### ISSUE TITLE
Add a command to allow new name

### ISSUE THREAD

**Issue by graywolf336** [Civcraft/NameLayer#13]
Would like to a command to allow a player's name to be changed to their new one. The reason is because I have a few players on my server who got upset when I mentioned name changes wouldn't work as we have restricted it due to Towny not supporting UUID's yet. So, I think it'd be amazing to have a command to get rid of a player's information in the database and thus resetting them or some new way to allow the usage of the player's new name.. If this is possible, how does one do this?

Thanks! And thanks for making the plugin available to us all!! :+1:

**Comment by ttk2** [comment]
if this is allowed it would just introduce the same problem, all the
plugins that depended on names would see the new named player as a new
person, so that would have to be handled yourself unless you want to recode
those plugins to be dependent on namelayer so that they can keep track (or
just use UUID's themselves)

**Comment by graywolf336** [comment]
I completely understand that and I've explained to the people who wanted their new names and they're willing to sacrifice their data in plugins, such as Towny, so they can use their new names..

**Comment by rourke750** [comment]
Alright, I'll try add it in anyways

**Comment by graywolf336** [comment]
Thanks :smile:

**Comment by spaceFountain** [comment]
Sorry about not getting to this. I'm thinking I'll probably try to do something at some point next week. In the mean time if you have access to the SQL server you can always manually remove the entries associated with the player. Eventually I plan to add a command that will allow admins to set the name of a player to anything they want. Possible defaulting to the Mojang name if none is provided. It's easiest cause I wouldn't have to worry about changing the groups at all. I'd probably delete the current association and then have NameLayer add it back in again so it would properly generate the entries to record how many times the name has been used. You aren't using foreign keys anywhere @rourke750  right?

**Comment by rourke750** [comment]
Nope.  I was going to get to this eventually just wansnt a priorty.

**Comment by erocs** [comment]
Make sure the command is disabled by default.

**Comment by spaceFountain** [comment]
This [pull request](https://github.com/Civcraft/NameLayer/pull/63) should do this. It mentions some of the issues with the command in the request so give it a read. This command should only be runnable or even show up to ops and players with the NameLayer.admin permission.
