### ISSUE TITLE
/nllm not useable for mods/members

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/NameLayer#130]
Caused by this pull:
https://github.com/Civcraft/NameLayer/pull/129
The error is here:
https://github.com/Civcraft/NameLayer/blob/master/src/vg/civcraft/mc/namelayer/command/commands/ListMembers.java#L46

The permission GROUPSTATS is actually for getting the complete stats on a group with /nlgs and not everyone in the group has this permission. Do mods and higher also have the permission member, so we could just change this to MEMBER? Or should we just add another permission?

@suirad

**Comment by suirad** [comment]
This was intended, see issue #86 (which should be closed).
From my understanding of that thread, /nllm was meant to be used by admin and above, or in other words, the same permission as GROUPSTATS.
@ttk2

**Comment by jjj5311** [comment]
@suirad I think the real issue is that GROUPSTATS was never given on a database basis... Even if you are OWNER on the group you still have to edit your permissions to give yourself GROUPSTATS.....

@ttk2 @erocs was this ever rolled out to the database with sql? I know we talked about it a long time ago

**Comment by ttk2** [comment]
I think we did, not sure.

**Comment by Maxopoly** [comment]
Some people were complaining that they own a group and can't run /nllm, but I just checked and can run it for the groups I own. It probably wasn't changed for older groups.

**Comment by erocs** [comment]
No, I believe we asked Rourke for the sql update statement but nothing was
ever run.

**Comment by rourke750** [comment]
My argument for that was that we can't actually know which Player Type should be the top tier for a group.  What needs to really be done is we need to change the you do not have permission to you do not have permission to run this command for this group.

**Comment by ttk2** [comment]
so whats the solution to this?

**Comment by erocs** [comment]
https://www.reddit.com/r/Civcraft/comments/3kbwsu/is_the_nllm_command_broken_for_anyone_else/cuwafly

**Comment by Maxopoly** [comment]
Make a script that gives at least the owner this permission, because in some cases noone has it.

**Comment by jjj5311** [comment]
The sql statement is somewhere in the GitHub repo

**Comment by erocs** [comment]
Ok, GROUPSTATS added to all OWNER role permissions.

N

**Comment by Maxopoly** [comment]
Fixed, please close
