### ISSUE TITLE
Create NameLayer Bungee Plugin

### ISSUE THREAD

**Issue by rourke750** [Civcraft/NameLayer#148]
Jus to set a users display name from bunge.

**Comment by ttk2** [comment]
so how does this work? does this fix the currently reported issues with namlayer tab auto complete not working?

**Comment by rourke750** [comment]
No you just need to update mercury for that.

**Comment by ttk2** [comment]
did mercury get updated?

**Comment by erocs** [comment]
Many times over but that has nothing to do with this issue...
