### ISSUE TITLE
Mercury messages aren't tokenized properly

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#155]
Currently NL uses a space to tokenize fields of Mercury messages. Group names or status messages could contain spaces. This will need to change when we standardize on a solid token for all plugins.

**Comment by ProgrammerDan** [comment]
Dependent on how Bukkit/Spigot tokenizes user-entered commands, group names should not be able to have spaces. https://github.com/Civcraft/NameLayer/blob/master/NameLayerMain/src/vg/civcraft/mc/namelayer/command/commands/CreateGroup.java

Finally, none of the existing NL-based Mercury messages include status messages: https://github.com/Civcraft/NameLayer/blob/master/NameLayerMain/src/vg/civcraft/mc/namelayer/listeners/MercuryMessageListener.java

That said though, totes agree.

**Comment by ttk2** [comment]
I assume we are using Unicode strings right? Or are we ASSCI?

**Comment by erocs** [comment]
Mercury transfers UTF-8.

**Comment by ttk2** [comment]
then we can use some super obscure deliminator character, actually considering unicode seems to have everything including the kitchen sink symbol can't we get a deliminator character?

**Comment by erocs** [comment]
The idea months ago was to move to serialized objects so plugins have no
need to perform the serialization/deserialization.

**Comment by Maxopoly** [comment]
Resolved by https://github.com/Civcraft/NameLayer/pull/220

Groups can no longer have pipes, by which we tokenize the messages.
