### ISSUE TITLE
Split permission string out into table

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#160]
The group permission string will someday run out of room. Just create a group_permission table with group_id and permission columns using both as the primary key. Join it in when you need to check a permission.

**Comment by erocs** [comment]
As Dan says, it would also need the player_type. Storing the date the permission was added might be nice too. Do we want who made the change? May as well keep it for auditing.

**Comment by Maxopoly** [comment]
Fixed as part of https://github.com/Civcraft/NameLayer/pull/191https://github.com/Civcraft/NameLayer/pull/191
