### ISSUE TITLE
Can't /nlag across shards in certain circumstances

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/NameLayer#169]
You get the invitation notice just fine, but when you use /nlag in a shard different from the invitation shard, you get the "You were not invited to that group." message.

**Comment by rourke750** [comment]
https://github.com/Civcraft/NameLayer/blob/master/NameLayerMain/src/vg/civcraft/mc/namelayer/listeners/MercuryMessageListener.java#L69

missing the add invite there.  @ProgrammerDan if you just want to snag it.

**Comment by ProgrammerDan** [comment]
Altering:

if the only member does /nlleg before the target player has accepted, the above issue occurs. /nlip and /nlag work fine if you don't do that in the middle.

**Comment by BlackXnt** [comment]
https://github.com/Civcraft/NameLayer/pull/173
