### ISSUE TITLE
Investigate - Inviting a player to a group he is already a member of is possible under some circumstances

### ISSUE THREAD

**Issue by BlackXnt** [Civcraft/NameLayer#177]

**Comment by Maxopoly** [comment]
Yes, because it seems to not be properly cached across shards

**Comment by BlackXnt** [comment]
The group?

**Comment by Maxopoly** [comment]
Yes, sometimes if you add people it wont get recached on other shards.

**Comment by ProgrammerDan** [comment]
@BlackXnt can you check if this is still an issue? I made some alterations to how groups are cached including their memberlist, so this should be solved. Let me know.

**Comment by BlackXnt** [comment]
I think it was fixed by https://github.com/Civcraft/NameLayer/commit/5a38b942d03724dc1a8af88c5167512a68364072

No one reported it since then.

**Comment by ProgrammerDan** [comment]
Yeah, that probably did. A+
