### ISSUE TITLE
Investigate - /nllg does not list all groups

### ISSUE THREAD

**Issue by BlackXnt** [Civcraft/NameLayer#178]

**Comment by Maxopoly** [comment]
nllg pulls them straight from the db, so thats kinda weird

**Comment by Maxopoly** [comment]
Seems like it's not telling other shards when a group was created and it doesnt appear on there until there is another reason to recache it, could that be the issue?

**Comment by ProgrammerDan** [comment]
@BlackXnt Is this still exhibiting?

**Comment by BlackXnt** [comment]
Safe to close this one.
