### ISSUE TITLE
/nllp doesn't auto complete names

### ISSUE THREAD

**Issue by BlackXnt** [Civcraft/NameLayer#179]

**Comment by ProgrammerDan** [comment]
Is this cross-shard or just shard local or neither?

**Comment by BlackXnt** [comment]
nllp doesn't even take a player name as an argument so I probably got confused when making this issue with another command.

**Comment by ProgrammerDan** [comment]
Ok, I'll close this then. Open a new one if you find the impacted command. Thanks!
