### ISSUE TITLE
/nllg counts weirdly

### ISSUE THREAD

**Issue by PatchyKnowly** [Civcraft/NameLayer#185]
I'm in 18 groups:
/nllg or /nllg 0 gives me 'page 1 of 0', showing 10 groups
/nllg 1 gives me 'page 2 of 1', showing 9 groups (including a duplicate of the last group)
/nllg 2 gives me 'page 3 of 2', though it doesn't list any groups
Any higher values give me 'page 3 of 2' and no groups

Confirmed with a friend who has less groups and it's the same for him, though his stops at '2 of 1', rather than '3 of 2'. It also lists our last group twice, for some reason, though the group in question is different for both of us.

Seemingly just a cosmetic issue though, so no hurry.
![160315-13 04 25](https://cloud.githubusercontent.com/assets/8378762/13778854/fc82442e-eaaf-11e5-92a9-c36014b4d019.png)

**Comment by Maxopoly** [comment]
Was the duplicate group ever merged?

**Comment by PatchyKnowly** [comment]
In my friend's case, his last group is 'nixsn', which was merged (specifically with chansnitch, with chansnitch being the group to be gone).
In my case, I'm not sure about the status of TreeKuns, as I was added to it by a friend who I can't get in touch with right now. 

As a test, I created the group 'xx' and it showed up at the end of my list with TreeKuns still being duplicated. I then merged 'containment' into 'xx' and checked my groups, but it only had the one entry, with TreeKuns still having two.
![160315-13 50 54](https://cloud.githubusercontent.com/assets/8378762/13779871/0459ea30-eab5-11e5-9a92-b8451407fe4b.png)

I guess I'll see if it changes after the next server restart.

**Comment by ProgrammerDan** [comment]
The Page 2 of 1 is just an index issue. I noted it during my last review but forgot to go back and fix it.

The duplicate just means I'll have to add dedup to the output; it's because of a merge and a bungled backend fix for an unrelated issue; I can look into it some more if it bugs you but it's safe to ignore.

**Comment by PatchyKnowly** [comment]
Nah, was just making sure it was noted somewhere.

**Comment by ProgrammerDan** [comment]
Perfect, thank you!

**Comment by Maxopoly** [comment]
Fixed as part of https://github.com/Civcraft/NameLayer/pull/191
