### ISSUE TITLE
Linking doesn't inherit members added after the fact

### ISSUE THREAD

**Issue by TrentWDB** [Civcraft/NameLayer#188]
There are two issues I'd like to discuss here.

The first is that, it seems if you link a subgroup to a supergroup, all the players of the supergroup are added to the subgroup. That's fine, but then (I haven't tested this heavily), once you add a new player to the supergroup, they're not automatically added to the subgroup. Logically, I think a subgroup should either always inherit members or the supergroup (which probably makes the most sense) or never inherit members and you have to add them individually.

Finally, before I was banned, we tried to create a defensive subgroup to protect all the towns in Aleph. Our reason for doing this is that we thought all members of every supergroup would be automatically added to the subgroup. So if the group ACD is a subgroup of Claystone, Heartland, Meridian, and Boundary, we'd have one auto updated giant group where we can all communicate in case of emergencies. It seems that each subgroup can only have 1 supergroup assigned to it, which personally I don't see any reason to restrict it to 1.

**Comment by ProgrammerDan** [comment]
Linking shouldn't move any members between groups. I'll doublecheck the code.

Merging removes all members from the source group into the destination group; but linking is not supposed to share that behavior iirc.

**Comment by TrentWDB** [comment]
Well it doesn't move the members, it just adds them. Initially after linking, both groups have all the members.

Really what I'm getting at is with the way linking works, its hard to imagine a proper use case. In the Meridian group, all members have permission to break blocks, so we have a subgroup called MeridianFactories or something well members no longer have that permission. This way, since they share the same members, we can restrict that permission from the factory group and they're unable to join and break our factories. However even this use case doesn't seem to be properly supported since members aren't automatically added to all subgroups after being initially linked.

**Comment by PatchyKnowly** [comment]
@TrentWDB 
Hm, a single subgroup sharing many supergroups would be extremely handy, and thinking about it, my suggestion https://github.com/Civcraft/NameLayer/issues/187, kinda requires that functionality, at least for the cooperation use case. I'm not sure how that slipped my mind, considering how long I spent writing the post. That said, multiple supergroups per subgroup would also kinda be sketchy without my suggestion too, otherwise the only thing you could really use it for without worry would be groupchat.

@ProgrammerDan 
I think he means that the inherited members of subgroups don't seem to be updating when a player is added/removed from a supergroup. I noticed this too very early on in civtemp but forgot about it. It might update on server restart, but I'm not sure, as the first thing I do after a restart is re-link groups, which is esentially manually updating them.

**Comment by ProgrammerDan** [comment]
@TrentWDB been thinking a lot on this. I will probably be shortly gutting sub/super group and largely recoding, we'll see. I may include some form of this functionality as I do that.

My thinking has mostly centered on Permission Flow, and I have two main ideas right now.

First, permission flows from subgroup _up_ to supergroup. E.g. When a group is linked as a subgroup, the members of the supergroup gain new privileges in the subgroup, but the members of the subgroup gain no privileges. In this model, a group can be supergroup to many groups but subgroup to only one. 
Thoughts:
  * Add a new special "permission class" called SubGroup. This defines the _maximum_ permission that flows up to the supergroup. Default would be approximately equivalent to MOD but without permission to invite other players. In this way the subgroup still controls how much a member of the supergroup can actually _do_.
  * When resolving the permission of a particular person, the following is done:
    * Get set of permissions for this person if they are a member of the group. If they are, use those permissions (no traversal).
    * If not a member, get the set of permissions of that group's SUBGROUP type. This is the "highest" permissible activity set for any members of any supergroup. Now traverse the supergroup chain; at each step in the chain compute the intersection of the current highest permissible activity set and the SUBGROUP activity set.
    * Also keep and maintain a merge-set of permissions based on individuals' level within the supergroup. E.g. if MEMBER in supergroup 1, but OWNER in highest-supergroup, use the merge of permissions from both levels. 
    * So we do two things: We find the broadest possible set of permissions for the user across the parent-chain (flowing up) and the smallest possible set of permissions for any user across the parent-chain (w/ limit).
    * Then, we compute the intersection of these two sets. Why do this last? Early intersection would remove later-permissions; so we must compute the limiting set (SUBGROUP perms) and the maximized set (member's own perms) to find the "largest" permission set for the user
    * Practical example: User isn't a member of subgroup. On supergroup they are MEMBER, but on that's supergroup's supergroup, they are MOD. The "maximized" set is CHEST, DOOR, BLOCK, INVITE. However, the first subgroup has SUBGROUP's permission set as DOOR, INVITE; the first supergroup has SUBGROUP permission of DOOR. Consequently, the "limiting set" is DOOR, so the only permission that the user has is DOOR, even though they are MOD on a supergroup "two levels above".

The second approach doesn't use a SUBGROUP special permission type. Instead, we just use a more traditional "overrides" approach. When checking a user's permission, we use their highest permission set along the Supergroup chain. This is what I think is currently in place, but it's not doing it correctly if I'm understanding folks. Here's how it should work:
  * Starting at group-of-interaction and for a particular player, find the maximized set of permissions for the player. At each group along the supergroup chain, find the merge of that user's "lower" permissions and the current group's permissions for that user, until the final supergroup is found. 
  * Practical example: User isn't a member of subgroup, but is a member of a middle supergroup and topmost supergroup (supergroup that has no supergroup). Initial permission is empty set {}. First supergroup we find they are MODS, and for that group permissions are "DOOR, CHEST, INVITE, BLOCK". However, in the second supergroup they are also MODS but have permissions "DOOR, BLOCK, INVITE, STATS". We merge the two, meaning the user's final permissions are "DOOR, CHEST, INVITE, BLOCK, STATS" on the group-of-interaction. 

If nothing else simply having consistent behavior would solve most problems. What do you think of these approaches? The first is a significant complexity bump for players to conceptualize, although it's not that complex from an ACL perspective.

Concerning multiple supergroups, I can tell you right now I don't intent to implement that. N:M group relationships just get messy within the concept of ACL. By restricting to 1:N, we simply need to better define how ACL filters down to subgroups; once that definition is firm and enforced through out the plugin we'll all be happier.

**Comment by TrentWDB** [comment]
Wow this is a lot to respond to. This type of permission flow is always pretty complicated and hard to visualize.

> First, permission flows from subgroup up to supergroup. E.g. When a group is linked as a subgroup, the members of the supergroup gain new privileges in the subgroup, but the members of the subgroup gain no privileges. In this model, a group can be supergroup to many groups but subgroup to only one. 

This is how I was originally thinking it should work. It makes the most sense to me that all members of a supergroup have all permissions of a subgroup. However, given this structure, I think it might be more helpful if a supergroup inherits all permissions of a subgroup *without* automatically adding all supergroup members as members of the subgroup like it currently does (or should be doing). I think this is what you were suggesting anyways. This way, you could manually add people to a subgroup and they can sort of be half members of your city since their permissions will be restricted to that of the subgroup. Also this way you can divide your town into squads or something where each squad can chat with each other privately. These are both use cases that I've been wanting.

<s>I feel like the current method where their rank is inherited from the supergroup is logical. Basically, if they're an admin in the supergroup, they should most likely have admin abilities in the subgroup. If they're an admin in the subgroup... then they have admin abilities in the subgroup. Maybe this is what you were saying as well, I'm not completely sure.</s>

After re-reading your post I think your method makes the most sense, especially if you want to allow multiple a subgroup to have multiple supergroups. And nothing is preventing you from adding admins as admins to the subgroup as well.

In response to your second post, this was something that I was going to bring up. I would like both of these options... somehow... It's probably too much to ask since it's not actually necessary, but one use we have for subgroups as it stands is our factories are subgrouped to a factory specific group where our members can only use them, not break them. Maybe you can have an inclusive subgroup and exclusive subgroup type thing.... No idea.

Anyways, I think if you have to choose one, your first idea is the best and most logical. Let me know if you have any questions about my responses, I kept dozing in and out of writing this.

**Comment by Maxopoly** [comment]
Linking was reworked to no longer inherit members, so closing this
