### ISSUE TITLE
[Major Issue] Restarting the server unlinks all sublinks

### ISSUE THREAD

**Issue by TrentWDB** [Civcraft/NameLayer#189]
Just as the title says. When the server restarts, all links between groups are dropped.

**Comment by ProgrammerDan** [comment]
This is truly mystifying. In my testing on other servers this does not occur.

**Comment by TrentWDB** [comment]
On other servers as in other shards? Or other servers as in testing servers?

This issue has been happening in Aleph. Have you been able to verify that I'm not just crazy?

**Comment by ProgrammerDan** [comment]
When I checked the db a few days ago it seemed to confirm. I do need to do some controlled testing, however. To my knowledge there is nothing that should be unlinking well-formed groups on start or stop, but I'll keep looking.

**Comment by Lcth** [comment]
Same for me in Bet, all linked groups get unlinked.

**Comment by ttk2** [comment]
are links not stored with the main group data? maybe its just not being loaded.

**Comment by ProgrammerDan** [comment]
They are a separate table. I think something is explicitly calling unlink when data is unloaded for save... possibly.

**Comment by PatchyKnowly** [comment]
Just want mention, this seems to be intermittent. I've currently got two supergroups I manage, one with three subgroups and one with one. Sometimes all of them unlink, but occasionally one or two of them will stay linked across a restart. Something sharding-related, maybe?

**Comment by ttk2** [comment]
that's possible, I have you tried doing this with a group that's never touched in another shard and then a group that is? 

That sounds like the fastest way to test that idea.

**Comment by PatchyKnowly** [comment]
I'm currently at the group limit, however, from what I've observed:  
super: a (created in aleph) / sub: chansn (created in bet) / sometimes unlinks
super: a (created in aleph) / sub: nixsn (created in bet)  / sometimes unlinks
super: a (created in aleph) / sub: nixdef (created in bet) / sometimes unlinks
super: nic (created in bet) / sub: nic-1 (created in zion) / has never unlinked so far

**Comment by ProgrammerDan** [comment]
@PatchyKnowly It's been a while, but could you set up a retest of this issue to ensure that Maxopoly's changes have fixed it?

**Comment by Maxopoly** [comment]
Just tried on CivTemp and it seemed to persist completly fine across restarts.

**Comment by ProgrammerDan** [comment]
Assuming this isn't an issue any longer, re-open if it is.

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/NameLayer/pull/225 will completly remove group linking anyway

**Comment by ProgrammerDan** [comment]
Cool.
