### ISSUE TITLE
Proper handling for transferring a group to a logged out player

### ISSUE THREAD

**Issue by spaceFountain** [Civcraft/NameLayer#19]
This may be because I'm a admin on my test server but I got an stack trace when I attempted to transfer a group to a made up user. The goal was to no longer be part of the group so I could test my pull request, but instead it triggered an exception. Can we add proper handling for normal players so they understand what went wrong and someway to test for devs?

Copied from an [issue](https://github.com/Civcraft/Citadel/issues/36) I incorrectly posted to Citadel

**Comment by rourke750** [comment]
https://github.com/Civcraft/NameLayer/commit/01ff0500f8d2759f755dbce4a1880799ea1a8e3f
