### ISSUE TITLE
/nl -- Add player final step lacks a prompt.

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/NameLayer#199]
Menu simply closes and displays no prompt, but does await user input. 

To reproduce: access a group via /nl and choose "Invite new member". Pick any level. An empty string is written to chat but no prompt.

**Comment by Maxopoly** [comment]
Fixed by https://github.com/Civcraft/NameLayer/commit/9be6c6e4fb85f450582d6bf733249bf3eeee36bd
