### ISSUE TITLE
/nl -- Plurality wrong on menu labels

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/NameLayer#200]
![image](https://cloud.githubusercontent.com/assets/409230/15989894/0168e9d2-3053-11e6-982c-815b44eb2cca.png)

Example above: Admin currently have this... should be "Admin**s**" currently have this, etc. Impacts all permission menus.

**Comment by Maxopoly** [comment]
Fixed by https://github.com/Civcraft/NameLayer/commit/9be6c6e4fb85f450582d6bf733249bf3eeee36bd
