### ISSUE TITLE
/nl -- Adding player to blacklist but give invalid player name

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/NameLayer#201]
![image](https://cloud.githubusercontent.com/assets/409230/15989900/3ec6dc8a-3053-11e6-86a0-6e79a1a13226.png)

As illustrated, giving a bad player name the prompt responds with "This group doesn't exist" which should likely be "This person has never played before" etc.

**Comment by Maxopoly** [comment]
I dont see how this could happen and cant reproduce http://puu.sh/pq0jP/12bef3074e.png

Are you sure that you didnt accidentally overlap this with another prompt which didnt have a message?

**Comment by Maxopoly** [comment]
After reading https://github.com/Civcraft/NameLayer/issues/202, I assume this issue is actually just another incarnation of https://github.com/Civcraft/NameLayer/issues/202

**Comment by ProgrammerDan** [comment]
99% confident. I'll see if I can give you a script to reproduce regularly
later on.

I was consistently reproducing by canceling a prior prompt and beginning a
different prompt of a different nature (group name vs player name). The
second prompt would fail.

**Comment by ProgrammerDan** [comment]
Ah yeah. Replying on mobile so lagging. Definitely an instance of 202.
