### ISSUE TITLE
MySQL Table creation errors

### ISSUE THREAD

**Issue by Azraq** [Civcraft/NameLayer#206]
Hello, first of all have all of the love from my network InsaneMC we've been looking for a plugin like this since forever and finally you guys are updating it , we appreciate your work!.

He's the little problems we've run into when we freshly installed Citadel on our server. 

 On First start there were a bunch of errors for MySQL table creation then after multiple restarts they vanished on their on, But some things were still missing from the tables created that we had to manually go through and put in the tables to get it to work, they're as follows.

**1-** had to create a table in namelayer database called 'group_invitation' with fields 'groupName' , 'uuid' and 'role'.  Didn't know their datatypes so made them all text.

**2-** had to create a new field in table 'faction' called 'last_timestamp' which has datatype TIMESTAMP (thankgod for field name), this missing field was gamebreaking.. each time we would reinforce a block it filled console with alot of errors.

**Using plugins:**
 - NameLayer-2.8.07
 - Citadel-3.5.3
 - CivModCore-1.4.41

**on minecraft 1.10**

**Comment by Maxopoly** [comment]
Your mysql version is outdated if that happens, use at least Maridb/mysql 5.6 and it will work

**Comment by Maxopoly** [comment]
Also if you "fixed" the tables manually with the wrong data type, you should delete and recreate them

**Comment by Azraq** [comment]
Aye, i will try that and get back to you. thankyou very much for your quick response :D

**Comment by ProgrammerDan** [comment]
Yeah, @Azraq I never had any luck using MySQL. We should just update the required dependencies to MariaDB; MySQL's handling of default values for TIMESTAMP is stuck in 1999 somewhere; MariaDB allows proper defaulting, so just use that.

Best of luck.
