### ISSUE TITLE
/nlcg lags entire shard for a few seconds (2 to 5-ish?)

### ISSUE THREAD

**Issue by gipsy-king** [Civcraft/NameLayer#217]
Could be abused to annoy a shard. I tested with someone in another shard, no lag reported (only tried once though, could be wrong).

My guess is that's some SQL locking, but I have never looked into the code.

**Comment by ProgrammerDan** [comment]
Thanks, fwiw we are aware but it's good to have this here too.

**Comment by ProgrammerDan** [comment]
Potentially addressed but may introduce externalities in #212

**Comment by ProgrammerDan** [comment]
https://github.com/Civcraft/NameLayer/pull/219

So check the more recent commits there; creategroup was issuing several dozen INSERT queries all of which also had subqueries ... anyway, once we merge the larger async changes that will go in as well.

**Comment by ProgrammerDan** [comment]
Should be entirely addressed by #219 ; I'll close after production timings confirm but testing shard timings  were definitely good.

**Comment by Maxopoly** [comment]
Async PR is a complete success, so this is no longer an issue.
