### ISSUE TITLE
the group Name_Layer_Special should not be protected

### ISSUE THREAD

**Issue by gipsy-king** [Civcraft/NameLayer#218]
1. create a new group for testing
2. reinforce some block
3. delete group

Problem:
The block(s) will be protected to `Name_Layer_Special`, cannot be broken with `/ctb` even though `/cti` shows it in green as if I had access to it.

Expected behaviour:
Anybody can break the blocks of `Name_Layer_Special`

**Comment by rourke750** [comment]
Expected behavior is actually Bonnie having any access to name layer
special

**Comment by Maxopoly** [comment]
Intended behavior
