### ISSUE TITLE
Allow players to set a default group - Very Low Priority

### ISSUE THREAD

**Issue by drjawa** [Civcraft/NameLayer#27]
This is a low priority for now. Essentially, once someone has chosen a group to be their default they can just use /ctf or /ctr without specifying group.

**Comment by jjj5311** [comment]
Made these changes today and tested them and it works

Looks like my NameLayer pull is borked somehow

https://github.com/Civcraft/NameLayer/pull/69

Here is the Citadel Pull

https://github.com/Civcraft/Citadel/pull/68
