### ISSUE TITLE
No method to toggle private group to public

### ISSUE THREAD

**Issue by ttk2** [Civcraft/NameLayer#35]
since this used to happen at the reinforcement level this leaves previously public groups unusuable as all their reinforcements are now private.

**Comment by rourke750** [comment]
They need to create a public group and change all the reinforcements to
that.

**Comment by ttk2** [comment]
using the merge command? how would that be done? could it be documented?

**Comment by rourke750** [comment]
yea

**Comment by ttk2** [comment]
so you make a new puglic group and merge the reinforcements from the old
group over?

**Comment by rourke750** [comment]
yes.

**Comment by ttk2** [comment]
ok then I will wait until you fix the group merge bug then recommend that

**Comment by erocs** [comment]
Is the group merge bug fixed so this can be closed out?
