### ISSUE TITLE
Create a promote command

### ISSUE THREAD

**Issue by rourke750** [Civcraft/NameLayer#44]
Instead of removing a player and and having to readd them create a promote command.

**Comment by jjj5311** [comment]
https://github.com/jjj5311/NameLayer/commit/17436aac232e1f410d663c2916a9c4f0581c7613

**Comment by GavJenks** [comment]
This is not quite the same as the other duplicate closed suggestion, unless you also add a DEmote command.  So if this is the way you are addressing it, please put in both. Just making sure.

**Comment by jjj5311** [comment]
@GavJenks  this would provide both
