### ISSUE TITLE
Suggested feature: blacklists

### ISSUE THREAD

**Issue by GavJenks** [Civcraft/NameLayer#46]
From Hantzu's thread -- also personally strongly believe in. A basic logical organization of groups in general, should be in any group management plugin in general.

**Comment by rourke750** [comment]
Ttk has expressed multiple times he does not want this.

**Comment by GavJenks** [comment]
Why not? Or can you provide links to where so I can read why he doesn't from the quote?

A search on reddit does not reveal anything, maybe Ii'm using the wrong terms. In fact, it has you saying you were already working on implementing them a year ago?
http://www.reddit.com/r/Civcraft/comments/1dtkoh/suggestion_for_citadel/

Also this thread, where ttk is reported as not even knowing if we already had blacklists
http://www.reddit.com/r/Civcraft/comments/1fqt98/on_the_last_end_portal/

**Comment by ttk2** [comment]
It allows Citadel to be easily used offensively. Not sure if its a good idea

**Comment by GavJenks** [comment]
I'm not sure I follow you. How does it allow citadel to become more offensive? It seems like exactly the opposite to me. You can already easily (and people do) spike vaults, for instance, with citadel as is. And whitelists are much more convenient for that, as well as for griefing and other offensive uses. Because you simply whitelist only yourself or your group of raiders / attackers, and it is now a problem for any and all other people.

Blacklist would be silly for spiking or griefing, because you'd have to add everybody in that town, and even then, some other guy from another town could just walk in and clean it all up.

Blacklist is inherently more optimistic, friendly, public-oriented, not the other way around. Or am I missing something?

**Comment by ttk2** [comment]
it takes all the effort out of enforcing any sort of rules, lets imagine
you could have public goods that only bad people could not use, then there
is no dilemma on if you should make goods public. No interesting discussion
with public netherfactories enabling griefers or private ones restricting
the public

**Comment by erocs** [comment]
Blacklists are easily bypassable by alts.

**Comment by GavJenks** [comment]
Ttk, as erocs points out, there are alts, and there are also new griefers all the time. Blacklists on a portal would require somebody to constantly be vigilant against these, in exactly the same way that a whitelister has to be constantly vigilant of new citizens in the alliance or whatever who need access to the portal. Nor do I see how this is any less of an "interesting" of a choice -- it's just a rule that lies in between the other two (unreinforced vs. whitelist) on a continuum. It seems no less inherently interesting than, say, a moderate political system does compared to a right or left wing one. It has some of the risks and some of the benefits of each.

**Comment by ttk2** [comment]
I still believe its too much perfect security, public resources should be
public, if you want things that selectivity deny people it should be more
costly than group management

**Comment by erocs** [comment]
Actually my point is that a Citadel blacklist is pointless because you'd
never be able to keep up with adding the new alts. A whitelist is
constrained in scope by only allowing explicit individuals access.

Blacklists for JukeAlert might be interesting as a way to have snitches
only alert if a specific set of individuals enters the alerting area.
Combined with the redstone pulse from the snitch it could create traps for
specific individuals.

**Comment by GavJenks** [comment]
I would also like to point out that blacklisting is effectively already possible with a very simple bot:
1) Keep a bot online at all times jumping occasionally or whatever, in a vault in the middle of nowhere.
2) Have it scan the online player list and notice instantly when anybody logs on via tab or chat-letter-tab (just like the skynet mod many people use). Immediately add them to a citadel group if they aren't already, unless they're on the blacklist stored clientside or on a website or something.

Including it as a feature is simply a convenience (and fairness to people without bots) courtesy to players, not even an actual functionally new feature per se.

(and I'm actually tempted to make that and share/sell it now that I thought it out here... not as an ultimatum lol, I just really want blacklist and realized I could probably do it in an evening or two)

**Comment by GavJenks** [comment]
...Also, we have one person saying "this is pointless you can never keep up and nobody would use it" and two other people saying "this is OP, everybody would use it and it's too easy and cheap for how awesome it is"

Different people saying "X will never work" for opposite reasons is often a green flag of a decently balanced idea =P

**Comment by erocs** [comment]
I'm saying citadel blacklisting is pointless and JukeAlert blacklisting
might have value. Please don't twist words.

Really I'm not sure why it hasn't been added if enough people want it and
can find a coder. I would just rather not remove effort from the current
deluge of bugs and the subsequent sharding effort. It seems there are
others helping now so we don't have to overload Rourke with this.

**Comment by rourke750** [comment]
@erocs It's so wonderful, I've spent my time reviewing instead of writing.

**Comment by rourke750** [comment]
@erocs Also Unless I'm thinking of something else couldnt that be turned into snitch spamming?

**Comment by erocs** [comment]
We have rate limiting for snitch spamming. The only other thing we should
do for that is persistence for jamute.

**Comment by GavJenks** [comment]
ah I legit did not see the distinction you were making being between citadel and jukealert, gotcha. Both/either would be useful to me.

I also certainly don't mean to be pushy or demanding with regard to timelines of actually implementing anything, and do plan at some point to finish figuring out the repositories to do some of the work on lots of things myself. Just debating feature value for now. If it were viewed positively but took 8 months due to low priority without "coding it yourself" then that would be fair and understandable.

**Comment by erocs** [comment]
The low priority work around here is all at the "Code it yourself" level,
thus why much of it gets dropped on the floor. For any dev work to be
completed there has to be a dev motivated to perform the work, not just
someone saying how nice something would be if it existed.

The next piece is, of course, whether or not the admins think it should be
active on the server. Unfortunately sometimes that isn't known until the
feature exists. Then when its examined and decided that it shouldn't be on
the server, devs can get agitated and demotivated even though their work
was useful by enabling a decision to be made.

**Comment by ttk2** [comment]
If more devs speced their proposals before writing them we would probably
not only have a much easier time telling people what we did and did not
want on the server we would probably get better and more stable code in
general. But that's time consuming and boring so very few people do.
