### ISSUE TITLE
Make owners not able to oust one another - voluntary leaving only

### ISSUE THREAD

**Issue by GavJenks** [Civcraft/NameLayer#47]
From Hantzu's thread -- I'm not sure I agree with this, but it is a reasonable argument. I.e. it creates unnecessary / pointless tension and mistrust and limits the plugin's usefulness for certain kinds of management, and if you do mistrust somebody, there's already the admin rank now for that.

**Comment by ttk2** [comment]
Pointless. Reinforcements could just be transfered to another group
instead.

**Comment by GavJenks** [comment]
What? The suggestion is that owners should not be able to remove other owners. If your co-owner removes you, then you've lost all control. You cannot then go and move the reinforcements to another group. You've simply lost them entirely. Thus, there exists no means by which two people can share ownership-level commands but not need to trust one another 100%.

It definitely has a point, the question is just whether as a design goal you want to have plugin-enforced trust and/or convenience, or whether you want the plugins to instill paranoia and/or create more work for a single owner.

**Comment by ttk2** [comment]
No I mean an attacker, who can no longer oust you from the group, can just
move the reinforcements and readd the appropriate people.

**Comment by GavJenks** [comment]
Oh I see, okay that's a good point.
