### ISSUE TITLE
Add ability to retract invites

### ISSUE THREAD

**Issue by GavJenks** [Civcraft/NameLayer#50]
From Hantzu's thread

**Comment by jjj5311** [comment]
Is this really something we want? invites already expire after reset and the player can be removed by the invitee

**Comment by rourke750** [comment]
Yea it is.  I know I've accidently added people to citadel groups, I
wouldn't want to haev to wait till restart to check if they accepted it.

**Comment by jjj5311** [comment]
Okay i will work on this now then

**Comment by rourke750** [comment]
Alright, thx for the help!

**Comment by jjj5311** [comment]
https://github.com/Civcraft/NameLayer/pull/55
