### ISSUE TITLE
Change a player's access level using /nlip without having to remove first with /nlrm

### ISSUE THREAD

**Issue by kwizzlehazzizle** [Civcraft/NameLayer#56]
I cannot for example, move someone from MODS to ADMINS without first removing them.  When I type "/nlip orion itaqi ADMINS" for example, it will tell me that itaqi is already part of the orion group.

In order to change someone's access level I have to remove them then add them.  I would like to be able to just do /nlip and not have to do /nlrm first.

**Comment by rourke750** [comment]
duplicate https://github.com/Civcraft/NameLayer/issues/49
