### ISSUE TITLE
Transferring group adds the receipt as an owner, but does not remove original group owner

### ISSUE THREAD

**Issue by drjawa** [Civcraft/NameLayer#60]

**Comment by jjj5311** [comment]
Do we want to remove the original owner or add them to a lower playertype?

**Comment by drjawa** [comment]
Citadel 2.0 would remove the tranferer from the group entirely. Should 
we do the same here?

**Comment by jjj5311** [comment]
I would assume so

**Comment by rourke750** [comment]
All so additionally to the group types there is an owner flag.  It transfer
the flag to that person.
