### ISSUE TITLE
Merge command has no effect

### ISSUE THREAD

**Issue by robbintt** [Civcraft/NameLayer#68]
Just did a merge of one group into another, both groups still exist when I do a /cti on blocks from either group. It did tell me merging was successful but seems to have had no effect.

**Comment by ttk2** [comment]
can you still access both groups? Does cti show the blocks still on
different groups?

**Comment by rourke750** [comment]
already fixed, check civtest

**Comment by robbintt** [comment]
Thanks, is there a branch that I can review in the future?

**Comment by ttk2** [comment]
will that work when we update Civcraft?
