### ISSUE TITLE
/nlgs allows all people in a group to view all info

### ISSUE THREAD

**Issue by jjj5311** [Civcraft/NameLayer#71]
I think this should be set to people with ADMINS or OWNER permission? and maybe mods?

No reason that members should be able to see who has what other permissions

**Comment by ttk2** [comment]
agreed, how was this overlooked before it was put online?

**Comment by jjj5311** [comment]
no idea working on a fix now

**Comment by rourke750** [comment]
Create a perm in namelayer and associate it woh the command.

**Comment by jjj5311** [comment]
Okay so someone will need to run the SQL to insert GROUPSTATS into the tier for OWNER and ADMINS...

**Comment by rourke750** [comment]
Owners can just give themselves the permission.

**Comment by jjj5311** [comment]
Okay cool, i didn't test that part but the rest works
