### ISSUE TITLE
/nldg and /nlsdg are too similar

### ISSUE THREAD

**Issue by WildWeazel** [Civcraft/NameLayer#77]
It's too easy to slip a letter and accidentally delete a group. Suggested change is to confirm before deleting a group.

**Comment by jjj5311** [comment]
#78

**Comment by WildWeazel** [comment]
To test:
Create a group
Use /nldg but do not confirm
After 15 seconds, verify the group still exists with /nllg or whatever
Use /nldg again and confirm within 15 seconds
Verify that group no longer exists

**Comment by dbear20** [comment]
Seems to work fine for me.

**Comment by ttk2** [comment]
that's good, everything else seem to work? I will stage it for tomorrow.
