### ISSUE TITLE
/ban is non-functional with NameLayer set player name

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#80]
Player A logs in/out of the server. Player changes name from A to B. Player logs in as B. Admin runs /ban B. Player not banned. Admin searches through logs, notices the player login log entry as A before NameLayer kicks in and changes the name, attempts /ban A and it works. banned-players.json contains the correct UUID and the player name B.

**Comment by rourke750** [comment]
I'm confused if the name was changed then why wouldn't you do /ban b to
begin with?

**Comment by erocs** [comment]
We did. It didn't work.

**Comment by rourke750** [comment]
What I meant was there name would show up as a.

**Comment by rourke750** [comment]
@erocs If there names becomes changed back to Player a after they changed it to B wouldn't you be typing the command /ban a

**Comment by erocs** [comment]
Maybe I got A and B messed up. Basically, player changes name. Running /ban for whatever name they show up as on the server (enforced by NameLayer) doesn't work. Running /ban for the name reported with their initial login log entry (before NameLayer enforcement) works.

**Comment by ttk2** [comment]
can namelayer control the /ban command or do we need to use /nlban which
will just run the /ban command with the right people

**Comment by erocs** [comment]
Unsure why this is happening so I can't say. It might be that NameLayer
just needs to hook another thing in MC to properly do name changes.

**Comment by erocs** [comment]
Also /pardon doesn't work.

**Comment by ttk2** [comment]
yes but that's a much lower priority bug :P

**Comment by rourke750** [comment]
I'll fix this tonight.

**Comment by rourke750** [comment]
Fixed in http://192.99.169.83:8080/job/NameLayer-master/109/

**Comment by ttk2** [comment]
has it been tested?

**Comment by rourke750** [comment]
I tested it on me.  it worked.  Not something that is possible on civtest though :/

**Comment by ttk2** [comment]
true enough, I have asked for people to run through the basics in the
changelog, will probably stage namelayer and factorymod tonight .
