### ISSUE TITLE
Citadel DB reinforcment entries remain after group deletion.

### ISSUE THREAD

**Issue by dbear20** [Civcraft/NameLayer#81]
After a group with blocks reinforced to it is deleted cti still displays those blocks as reinforced but they can be removed without breaking them multiple times. Is this how its suppose to function or does it take some time or a server restart for the citadel DB to be updated?

**Comment by rourke750** [comment]
https://github.com/Civcraft/NameLayer/wiki#disabling-or-deleting-groups

**Comment by WildWeazel** [comment]
That section is contradictory, it gives the same commands for temporary disabling and deleting/disciplining a group. What's supposed to happen to the reinforcement materials in each case?

**Comment by rourke750** [comment]
It stays reinforced

**Comment by dbear20** [comment]
Ok so if you use /cti on a block that was reinforced by a group that is now deleted it's suppose to say it's still reinforced but it can be removed with just one break?

**Comment by jjj5311** [comment]
are you in bypass mode?

**Comment by rourke750** [comment]
No it takes the same amount of time

**Comment by jjj5311** [comment]
also why did we add a control to confirm deletion if it only disables the group?

**Comment by rourke750** [comment]
It doesn't.

**Comment by WildWeazel** [comment]
then the wiki is inaccurate...

**Comment by ttk2** [comment]
Roruke I don't think you should combine group disable and delete in the
same block, I understand what it means just  fine but its obviously
confusing for everyone else.

What this says is that when a group is deleted it leaves the reinforcements
just impossible to access

**Comment by dbear20** [comment]
No i did not have bypass enabled, but i do have some dev permissions which i think might be messing with it because i can break blocks that are reinforced without wearing the reinforcement down and i don't get the reinforcement material back. Note this is only on civtest that i have the extra permissions.

**Comment by ttk2** [comment]
so on Civcraft you can break blocks from your previously deleted group
without bypass, you don't get the material but you don't have to actually
break them either?

**Comment by rourke750** [comment]
Lol. So much confusion from everyone.

**Comment by ttk2** [comment]
that's what bugs + bad docs do

**Comment by rourke750** [comment]
No bugs and I fixed the wiki like 5 hours ago when I saw it was wrong.

**Comment by dbear20** [comment]
I haven't tried deleting a group on the live server yet, i'll do that in the morning, the odd behavior is on the testing server but i think it might have to do with me having more permissions than most other people.

The behavior i get on civtest is i reinforce some blocks and then i when i break them with bypass on or off i get the block but i don't get the reinforcement material when i use bypass and i only have to break it once when bypass is off. This behavior is the same whether the group had been deleted or not. There is something buggy but i'm not sure its worth tracking down and fixing because its only the admins that would ever encounter it.
