### ISSUE TITLE
Log player login name changes

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#82]
When a player logs in, if NameLayer is changing their name because they have changed their name with Mojang, please log it.

[NameLayer] ABC (uuiduuid-uuid-uuid-uuid-uuiduuiduuid) name changed to XYZ
ABC is their current Mojang name. XYZ is the name they will be forced to use on the server.

This is somewhat orthogonal to #80, as it would allow faster banning of the account's current Mojang name. Even if #80 is fixed, it will allow easier mapping since the initial login entry with their UUID contains their Mojang name and the very next "logged in" entry contains their NameLayer name with no UUID.

**Comment by rourke750** [comment]
In newest build
