### ISSUE TITLE
Group shows itself twice in listing, player tries to merge them which deletes it

### ISSUE THREAD

**Issue by drjawa** [Civcraft/NameLayer#83]

**Comment by rourke750** [comment]
wut.

**Comment by drjawa** [comment]
Yeah, figuring this one out might be tricky.

**Comment by rourke750** [comment]
I think we should just ignore it.

**Comment by drjawa** [comment]
Well, the player has lost access to all their reinforcements.

**Comment by rourke750** [comment]
Can you tp to an area where there were his reinforcements were and see what
group they are on.  Worst comes to worse we need to load a backup and find
what the group id was and manually fix it.

**Comment by drjawa** [comment]
I'll ask and report back

Excerpts from rourke750's message of 2015-03-08 16:05:28 -0700:
> Can you tp to an area where there were his reinforcements were and see what
> group they are on.  Worst comes to worse we need to load a backup and find
> what the group id was and manually fix it.

**Comment by ttk2** [comment]
could this be related 2015-03-08 22:54:04 [WARN] com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '33dea67f-bd63-4ae4-9dcc-3fa41d-c695aa-66755' for key 'uq_meber_faction'

**Comment by rourke750** [comment]
They most likely fucked up their group.  Can you load up a back up and ask what the group was called.  We need to find what the group id was and manually create a new group and then through mysql set the group id to the new group we created.  After that transfer the group to the player and problem solved.

**Comment by ttk2** [comment]
list steps please? Also how do I dig stuff out of a sqldump?

**Comment by rourke750** [comment]
I'll prob just do this with erocs so if you want to just download a backup or something for him i can have him do it all.

**Comment by ttk2** [comment]
he should just be able to gab the latest sqldump trivially we need to
figure out how old of a backup we need to restore.

**Comment by rourke750** [comment]
The day before he merged should work. Its just needed to find a single
field.

**Comment by rourke750** [comment]
@drjawa I'm still waiting on info any luck on this?

**Comment by ttk2** [comment]
this is fixed now, I have the sqldump backup, what do I need to do with it?

**Comment by ttk2** [comment]
I mean the problem is fixed now but we still have cleanup.

**Comment by rourke750** [comment]
Did you get the information from the player?

**Comment by ttk2** [comment]
what do we need from them?

**Comment by rourke750** [comment]
https://github.com/Civcraft/NameLayer/issues/83#issuecomment-77845946

**Comment by rourke750** [comment]
https://github.com/Civcraft/NameLayer/commit/6c567fe81a7ee42e5299a7d37f1fc9732b887e6c
