### ISSUE TITLE
Stop players from merging a group into itself.

### ISSUE THREAD

**Issue by rourke750** [Civcraft/NameLayer#84]
This can cause issues where the group is deleted effectively making a poorer version of the delete command but causes more issues as well as not really making the risks known to the player.

**Comment by jjj5311** [comment]
tested on civtest and everything looks good to go

http://imgur.com/0rcYKb3

**Comment by ttk2** [comment]
good because it just went online :P

**Comment by drjawa** [comment]
Just occurred again.

**Comment by jjj5311** [comment]
so is this not really online??

there is no way they should have been able to merge a group with itself

**Comment by drjawa** [comment]
This should be online. I'm checking for stacktraces now

**Comment by rourke750** [comment]
Lets wait for the player to complain and see what's wrong.

**Comment by drjawa** [comment]
They did, I checked the coordinates of some of their reinforcements and
/cti shows the group has changed to NameLayer special.

**Comment by rourke750** [comment]
Ask them what happened.  What the previous group was what they changed it
to.  Then actually tell me this time...

**Comment by drjawa** [comment]
They saw one group listed twice, they merged them, then they lost access.

**Comment by rourke750** [comment]
https://github.com/Civcraft/NameLayer/commit/6c567fe81a7ee42e5299a7d37f1fc9732b887e6c
