### ISSUE TITLE
/nllm <group> <player-type> is usable by anyone if they are a part of the group

### ISSUE THREAD

**Issue by Rekvia** [Civcraft/NameLayer#86]
Anyone can use /nllm as long as they are in the group regardless of permissions. There is no permission variable to toggle for this command, but /nlgs can be toggled with the GROUPSTATS perm. The two commands do almost the same thing. Allowing all members of a group access to /nllm essentially bypasses /nlgs permissions for a playertype. Merging permissions for /nllm with GROUPSTATS would fix this issue or giving /nllm its own seperate permission.

**Comment by ttk2** [comment]
yup that sounds like a bug, thanks for reporting.

**Comment by TealNerd** [comment]
https://github.com/Civcraft/NameLayer/pull/93

**Comment by jjj5311** [comment]
this ever get sorted out?

**Comment by rourke750** [comment]
I do not believe so. It would be easy enough to check.

**Comment by ProgrammerDan** [comment]
If I recall my own testing you can only view the list for people of your group or lower, e.g. MODS can view the list of MODS and MEMBERS, members can view the list of MEMBERS but not MODS, etc.

but I must confess non-authoritative knowledge, so it's worth testing.

**Comment by jjj5311** [comment]
https://github.com/Civcraft/NameLayer/blob/master/src/vg/civcraft/mc/namelayer/command/commands/ListMembers.java#L46

Doesn't appear to be anything checking permissions and/or senders type in the group

**Comment by suirad** [comment]
I'm about to whip this up, what is the desired result? Just to use the perms for group stats?

**Comment by ttk2** [comment]
perms sounds good.

**Comment by suirad** [comment]
Pull submitted

**Comment by Maxopoly** [comment]
Fixed by https://github.com/Civcraft/NameLayer/pull/129 please close
