### ISSUE TITLE
Not updated to 1.8.3

### ISSUE THREAD

**Issue by j0ach1mmall3** [Civcraft/NameLayer#87]
Namelayer doesn't provide support for Spigot 1.8.3.
Please add it soon, it would be greatly appreciated!

**Comment by rourke750** [comment]
Unfortunately unless I can find a way to trick maven we wont be able to support versions beyond what we are currently running.

**Comment by ttk2** [comment]
our plan is to move forward soon, why can't we have a 1.8 branch though?

**Comment by WildWeazel** [comment]
What's the problem with Maven? The fixed dependency version? We could use a variable for that, or just change it locally.

**Comment by rourke750** [comment]
Its the nms code that gets changed every few versions or when ever there is
a major mc change. I need different versions of spigot, if you can get the
pom to use a 1.8.3 spigot as well as the 1.8.1 please do.

**Comment by rourke750** [comment]
@j0ach1mmall3 Hey the latest version should work for apigot 1.8.3
