### ISSUE TITLE
Tab autocomplete is case-sensitive...

### ISSUE THREAD

**Issue by Sanwi** [Civcraft/NameLayer#96]
When typing a command in, using the tab key to autocomplete is case-sensitive, but the commands do not require that. For example, a group named "Blah" can be autocompleted like this: "/nlip Bl<tab>", but NOT like this: "/nlip bl<tab>". However, typing in "/nlip blah" will be accepted. It's really annoying =P

**Comment by rourke750** [comment]
I'll try look into this.  Is this specific to this command or all?

**Comment by jjj5311** [comment]
All commands, also case sensitive for peissiomx

**Comment by rourke750** [comment]
I'll crack this now i guess

**Comment by Sanwi** [comment]
Thanks, Rourke!
