### ISSUE TITLE
Usernames are not changed on join.

### ISSUE THREAD

**Issue by justcool393** [Civcraft/NameLayer#97]
There does not seem to be any errors that occur, and it just seems to fail silently when trying to change names.

Minecraft server version: 1.8.3
Server version: git-Spigot-1d14d5f-ba32592
API version implemented: 1.8.3-R0.1-SNAPSHOT

**Comment by rourke750** [comment]
Can you post any errors related to NameLayer even on startup.  There was
the one correct?

**Comment by justcool393** [comment]
After removing the leftover tables, there were no errors.

[Log on restart with database creation][1]

At this point, I shut down the server and changed my name in the `Name_player` database and verified it was changed.

I restarted the server.

[Log after restart][2]

[1]: http://pastebin.com/sPwpzk5c
[2]: http://pastebin.com/i73a46VD

**Comment by rourke750** [comment]
@justcool393 Thx for bringing this to my attention.  If you ever need help feel free to pm but if it's a plugin issue its better to post on github.  

Fixed: https://github.com/Civcraft/NameLayer/commit/a0960e0dd50a532d7981e426f7073d9ea998c7ab

Jar: Uh server is having issues will post jar alter.

**Comment by ttk2** [comment]
Jeinkins is up, but the build is failing.

**Comment by rourke750** [comment]
http://192.99.169.83:8080/job/NameLayer-master/127/
